name: Build and Deploy Services

on:
  push:
    branches: ["prod", "dev"]

permissions: write-all

jobs:
  deploy:
    env:
      TF_CLOUD_ORGANIZATION: ${{ github.repository_owner }}
      TF_API_TOKEN: ${{ secrets.TFE_TOKEN }}
    name: "Build and Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Check state of initial-deploy workflow
        id: check_state
        run: |
          echo "initial_deploy_state=$(gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/workflows/initial-deploy.yml | jq -r '.state')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Checkout
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        uses: actions/checkout@v3

      - name: Get next version
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: calver
          increment: patch

      - name: Set variables
        id: setvars
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        run: |
          if [[ "${{github.base_ref}}" == "dev" || "${{github.ref}}" == "refs/heads/dev" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi

          if [[ "${{github.base_ref}}" == "prod" || "${{github.ref}}" == "refs/heads/prod" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          fi

      - name: Create release
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        uses: "actions/github-script@v6"
        env:
          VERSION: ${{ steps.version.outputs.version }}
        with:
          github-token: "${{ github.token }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.VERSION,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.VERSION,
                target_commitish: '${{ steps.setvars.outputs.environment }}'
              });
              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: Fetch workspace id
        id: fetch_workspace_id
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        run: |
          workspace_id=$(curl \
          --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
          --header "Content-Type: application/vnd.api+json" \
          --request GET \
          https://app.terraform.io/api/v2/organizations/${{ github.repository_owner }}/workspaces/${{ github.event.repository.name }}-${{ steps.setvars.outputs.environment }} | jq -r '.data.id')
          echo "workspace_id=$workspace_id" >> $GITHUB_OUTPUT

      - name: Lookup Project ID
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        id: lookup_project_id
        run: |
            curl \
            --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request GET \
            --output project_output.txt \
            https://app.terraform.io/api/v2/organizations/${{ github.repository_owner }}/projects
            echo "project_id=$(jq -r --arg name '${{ vars.TFE_PROJECT }}' '.data[] | select(.attributes.name | test($name; "i")) | .id' project_output.txt)" >> $GITHUB_OUTPUT

      - name: update version
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        run: |
          curl \
            --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            "https://app.terraform.io/api/v2/workspaces/${{ steps.fetch_workspace_id.outputs.workspace_id }}/vars" | jq -r '.data[] | select(.attributes.key == "VERSION") | .id' > var_id

          VAR_ID=$(cat var_id)
          curl \
            --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request DELETE \
            https://app.terraform.io/api/v2/workspaces/${{ steps.fetch_workspace_id.outputs.workspace_id }}/vars/$VAR_ID

          cat > payload.json <<EOF
          {
            "data": {
              "type":"vars",
              "attributes": {
                "key":"VERSION",
                "value":"${{ steps.version.outputs.version }}",
                "description":"code version",
                "category":"terraform",
                "hcl":false,
                "sensitive":false
              },
              "relationships": {
                "workspace": {
                  "data": {
                    "id":"${{ steps.fetch_workspace_id.outputs.workspace_id }}",
                    "type":"workspaces"
                  }
                }
              }
            }
          }
          EOF
          curl \
          --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data @payload.json \
          https://app.terraform.io/api/v2/vars

      - uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.1.1
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        id: upload
        with:
          workspace: ${{ github.event.repository.name }}-${{ steps.setvars.outputs.environment }}
          directory: .

      # ────────────────────────────────────────────────
      # ⛓️ GHCR Build & Push Steps
      # ────────────────────────────────────────────────

      - name: Log in to GHCR
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/$(basename ${{ github.repository }}):${{ steps.version.outputs.version }} .

      - name: Push Docker image to GHCR
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/$(basename ${{ github.repository }}):${{ steps.version.outputs.version }}

      - name: Tag and Push 'latest' Docker image
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/$(basename ${{ github.repository }}):${{ steps.version.outputs.version }} \
                     ghcr.io/${{ github.repository_owner }}/$(basename ${{ github.repository }}):${{ steps.setvars.outputs.environment }}-latest
          docker push ghcr.io/${{ github.repository_owner }}/$(basename ${{ github.repository }}):${{ steps.setvars.outputs.environment }}-latest

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.1.1
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        id: apply-run
        with:
          workspace: ${{ github.event.repository.name }}-${{ steps.setvars.outputs.environment }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          plan_only: false